using System;
using System.Collections.Generic;

namespace ReunionWeb.Models
{
    public partial class Mcarga
    {
        public string? Fecha { get; set; }
        public string? Grupo { get; set; }
        public string? Área { get; set; }
        public string? Turno { get; set; }
        public string? CodEquipo { get; set; }
        public string? Nam { get; set; }
        public string? Nash { get; set; }
        public string? Nrr { get; set; }
        public string? Nlf { get; set; }
        public string? Ctr { get; set; }
        public string? Inc { get; set; }
        public string? Fci { get; set; }
        public string? Fte { get; set; }
        public string? Ld { get; set; }
        public string? Lt { get; set; }
        public string? Cocteleras { get; set; }
        public string? Asiento { get; set; }
        public string? Sb { get; set; }
        public string? Frenos { get; set; }
        public string? Fm { get; set; }
        public string? Ri { get; set; }
        public string? Cauchos { get; set; }
        public string? Nacv { get; set; }
        public string? Batería { get; set; }
        public string? Horquillas { get; set; }
        public string? Capot { get; set; }
        public string? Fam { get; set; }
        public string? Fr { get; set; }
        public string? Fah { get; set; }
        public string? Gobernador { get; set; }
        public string? Extintor { get; set; }
        public string? Ar { get; set; }
        public string? Corneta { get; set; }
        public string? Retrovisores { get; set; }
        public string? Cs { get; set; }
        public string? Gg { get; set; }
        public string? Be { get; set; }
        public string? Prc { get; set; }
        public string? Ppi { get; set; }
        public string? A1 { get; set; }
        public string? A2 { get; set; }
        public string? A3 { get; set; }
        public string? A4 { get; set; }
        public string? A5 { get; set; }
        public string? A6 { get; set; }
        public string? Obs1 { get; set; }
        public string? Obs2 { get; set; }
        public string? Obs3 { get; set; }
        public string? Obs4 { get; set; }
        public string? Obs5 { get; set; }
        public string? Obs6 { get; set; }
        public string? Obs7 { get; set; }
        public string? Obs8 { get; set; }
        public string? Obs9 { get; set; }
        public string? Obs10 { get; set; }
        public string? Obs11 { get; set; }
        public string? Obs12 { get; set; }
        public string? Obs13 { get; set; }
        public string? Obs14 { get; set; }
        public string? Obs15 { get; set; }
        public string? Obs16 { get; set; }
        public string? Obs17 { get; set; }
        public string? Obs18 { get; set; }
        public string? Obs19 { get; set; }
        public string? Obs20 { get; set; }
        public string? Obs21 { get; set; }
        public string? B1 { get; set; }
        public string? B2 { get; set; }
        public string? B3 { get; set; }
        public string? B4 { get; set; }
        public string? B5 { get; set; }
        public string? CargaInic { get; set; }
        public string? CargaFin { get; set; }
        public DateTime? HoraInic { get; set; }
        public DateTime? HoraFin { get; set; }
        public string? Harricana { get; set; }
        public string? Pasadores { get; set; }
        public string? Alternador { get; set; }
        public string? Temp { get; set; }
        public string? Aireacond { get; set; }
        public string? Presaceite { get; set; }
        public string? Bornes { get; set; }
        public string? Machbrake { get; set; }
        public string? Mordaza { get; set; }
        public string? Clamjaiba { get; set; }
        public string? Mgiro { get; set; }
        public string? Hytobo { get; set; }
        public string? Volt { get; set; }
        public string? Comp { get; set; }
        public string? Gasoil { get; set; }
    }
}
